Update get-dump.yml

diff --git a/.github/workflows/get-dump.yml b/.github/workflows/get-dump.yml
--- a/.github/workflows/get-dump.yml
+++ b/.github/workflows/get-dump.yml
@@ -104,7 +104,7 @@ jobs:
             i=0
             while read line; do
               which wget
-              wget -v -O - $line | grep -oE "question\s[0-9]+" > ./tmpr || echo "Error"
+              wget -q -O - $line | grep -oE "question\s[0-9]+" > ./tmpr || echo "Error"
               if [ $? == 0 ] && [ "$(cat ./tmpr|head -n 1  | tr  ' ' '-')" != "" ];then
                 fname=$(cat ./tmpr|head -n 1  | tr  ' ' '-').pdf ;
                 echo "file name : $fname ------>"
