Update get-dump.yml

diff --git a/.github/workflows/get-dump.yml b/.github/workflows/get-dump.yml
--- a/.github/workflows/get-dump.yml
+++ b/.github/workflows/get-dump.yml
@@ -102,9 +102,8 @@ jobs:
           if [ -s "./${{ inputs.config }}" ]; then
             i=0
             while read line; do
-              echo $line
-              # Enhanced wkhtmltopdf command with error handling
-              wget -q -O - $line | grep -oE "question\s[0-9]+" > ./tmpr
+              which wget
+              wget -v -q -O - $line | grep -oE "question\s[0-9]+" > ./tmpr || echo "Error"
 
               if [ $? == 0 ] && [ "$(cat ./tmpr|head -n 1  | tr  ' ' '-')" != "" ];then
                 fname=$(cat ./tmpr|head -n 1  | tr  ' ' '-').pdf ;
