Update get-dump.yml

diff --git a/.github/workflows/get-dump.yml b/.github/workflows/get-dump.yml
--- a/.github/workflows/get-dump.yml
+++ b/.github/workflows/get-dump.yml
@@ -42,10 +42,17 @@ jobs:
           i=0
           while read line; do
             # Enhanced wkhtmltopdf command with error handling
-            if ! bash -c "(echo _______ For line $((++i)) _____; wkhtmltopdf --no-stop-slow-scripts --javascript-delay 1000 $line 2>&1 | tee -a ./report)"; then
-              echo "Error occurred: Rerun \"wkhtmltopdf --no-stop-slow-scripts --javascript-delay 1000 $line\" " >> ./report
-            fi
-            sleep $(shuf -i 3-8 -n 1)
+            if (wget -q -O - $line | grep -oE "question\s[0-9]+" > ./tmpr || echo $?); then 
+              fname=$(cat ./tmpr|head -n 1  | tr  ' ' '-').pdf ; 
+              rm ./tmpr ;
+              if ! bash -c "(echo _______ For line $((++i)) _____; wkhtmltopdf --no-stop-slow-scripts --javascript-delay 1000 $line $fname.pdf 2>&1 | tee -a ./report)"; then
+                echo "Error occurred: Rerun Line : $((++i)) >> ./report
+              fi
+              sleep $(shuf -i 3-8 -n 1)
+            else 
+              echo $line >> ./reprocess ;
+              continue;
+            fi 
           done < ./source.txt
           mv *.pdf q/
           grep -i error ./report >> $GITHUB_STEP_SUMMARY
@@ -66,7 +73,7 @@ jobs:
       # Step 6: Commit and push the report and any generated files
       - name: Commit and push changes
         run: |
-          git add report *.pdf
+          git add report reprocess *.pdf
           if git diff-index --quiet HEAD; then
             echo "No changes to commit."
           else
